.github/CODEOWNERS
Ensure that code owners are assigned as reviewers automatically and are required to review PRs touching that code before it can be merged. Basics:
1. TLs are responsible for their sections.
2. TPL can approve PRs as well if necessary.
3. Access to important files is restricted to TPL & mentor.
=> feat(M): add code owners file

frontend/public/manifest.json, frontend/public/robots.txt, frontend/src/app/sitemap.ts, frontend/src/lib/metadata.ts
- The application lacked proper SEO configuration and metadata
- No sitemap.xml or robots.txt files were present
- Missing proper meta tags for search engines and social sharing
- No structured data for better search engine understanding
Added comprehensive SEO and metadata configuration:
1. **Metadata Configuration** (`frontend/src/lib/metadata.ts`):
```typescript
const baseMetadata = {
title: t('metaTitle') || 'Coach AI',
description: t('metaDescription') || 'AI-powered coaching platform for leadership development',
keywords: ['leadership', 'coaching', 'AI', 'training', 'development', 'feedback', 'management'],
metadataBase: new URL(BASE_URL),
alternates: {
canonical: localizedUrl,
languages: {
'en-US': url,
de: `${BASE_URL}/de${path}`,
'x-default': url,
},
},
// ... other metadata
}; …
```
=> feat(F-177): SEO Improvement

backend/app/connections/gemini_client.py, backend/app/services/voice_analysis_service.py, backend/pyproject.toml, backend/uv.lock
Voice analysis is needed for the real-time suggestions
Implemented a voice analysis service using Gemini from file and uri. If it's from uri, it downloads the audio as a temp, which it later removes. For that, created a Gemini client/connection. Closes #94 
Tested manually if the `voice_analysis_service.py` functions work with a local .mp3 file and a sample audio uri. Tests will probably follow when this service gets integrated with the other functionalities in the backend
=> Voice analysis using Gemini

backend/app/.env.example, backend/app/config.py, backend/app/main.py, frontend/env.d.ts, frontend/src/app/[locale]/(auth)/login/components/SignInForm.tsx, frontend/src/lib/metadata.ts, frontend/src/middleware.ts
Minor issues:
1. Production deployment is failing due to misconfigured CORS.
2. No logging for backend code.
3. Missing env vars in example files for Supabase Auth setup.
1. Configure CORS to work with standard local setup by default with option to overwrite with an env var.
2. Add logging module with some basic configuration.
3. Added missing env vars.
No additional changes necessary anywhere. Environment variables are already on the prod deployment.
Already tested by deploying to prod.
None.
=> Minor fixes to authentication setup

backend/app/routers/conversation_category_route.py
Link resolved issues with `#`.
What was the state of the backend before this PR? What problem are you solving?
#254 
What architectural/code changes did you make?
Include:
- Important design decisions.
- Code snippets (if relevant).
- Usage examples (e.g. for new libraries, background jobs).
- Screenshots (only if there’s a UI change like Swagger updates).
- Does this affect any APIs (add/remove/change endpoints)?
-  Secures the Get Conversation Category endpoint
- Do other systems or teams depend on this behavior?
-  Needs a logged in User or Admin
- Is there another PR (frontend or backend) that must be merged first?
- Did you deprecate/remove any feature or behavior?
How can someone test your changes locally?
Please include:
- Any required environment variables.
- Sample curl/Postman …
=> secured get route for conversation category

backend/app/data/dummy_data.py, backend/app/models/conversation_category.py, backend/app/models/conversation_scenario.py, backend/app/routers/conversation_category_route.py, backend/app/services/realtime_context_service.py
Skipped
Nothing
tested locally
> Keep the PR as a **draft** until all of the following are checked and you're confident it's ready for review.
- Which parts of the code need extra attention?
- Is this a functional change, a refactor, or a cleanup?
- Any known issues or follow-up work?
=> Change Category IDs from UUID to String

backend/app/main.py, backend/app/routers/app_config_route.py, backend/app/routers/auth_route.py, backend/app/routers/conversation_category_route.py, backend/app/routers/conversation_scenario_route.py, backend/app/routers/rating_route.py, backend/app/routers/review_route.py, backend/app/routers/scenario_preparation_route.py, backend/app/routers/session_feedback_route.py, backend/app/routers/session_route.py, backend/app/routers/session_turn_route.py, backend/app/routers/user_confidence_score_route.py, backend/app/routers/user_goals_route.py, backend/app/routers/user_profile_route.py, backend/app/routers/user_profile_stats_route.py
=> fix(M): Replace routes urls

backend/app/services/session_feedback_service.py
The feedback preparation for positive and negative examples should only consider User quotes, not the AI ones.
=> Feedback only consider User Transcript Quotes

frontend/src/app/[locale]/(standalone)/simulation/[id]/components/SimulationPage.tsx
Mic mute button on /simulation page also muted ai response.
=> fix(M): mic mute button only mutes input, not ai response

backend/app/data/populate_dummy_data.py
Until the dockered supabase PR is merge, this will break local development. Leaving commented for now.
=> hotfix(M): Disable demo users population

backend/app/services/scenario_preparation_service.py, backend/app/services/session_feedback_service.py
=> Make AI calls concurrent

frontend/src/app/[locale]/(main)/admin/page.tsx
=> fix(M): fix admin page for admin

frontend/src/components/common/BackButton.tsx
- Although the width of the back button is correct, the underlying link spans across the whole horizontal width
- Adjusted total width of the back button
_No implications_
- Check the width of the back button
_No remarks_
=> Adjust width of the back button

docker-compose.yml
=> fix(M): update DEV_MODE_MOCK_USER_ID to admin as default value

backend/app/routers/app_config_route.py, backend/app/services/app_config_service.py
Link resolved issues with `#`.
What was the state of the backend before this PR? What problem are you solving?
Closes: #491 
Refactored the App_config Route and secured the get  endpoint for user and admin access
What architectural/code changes did you make?
Include:
- Important design decisions.
- Code snippets (if relevant).
- Usage examples (e.g. for new libraries, background jobs).
- Screenshots (only if there’s a UI change like Swagger updates).
- Does this affect any APIs (add/remove/change endpoints)?
- Do other systems or teams depend on this behavior?
- Is there another PR (frontend or backend) that must be merged first?
- Did you deprecate/remove any feature or behavior?
How can someone test your changes locally?
Please include:
- Any required environment variables.
- Sample …
=> refactored app_config and secured get endpoint for users also to access

frontend/src/styles/globals.css
Select component causes layout shift
Add proposed solution to globals.css
No implications on other tasks. Only UI update.
Ensured layout looks correct.
review globals.css and test the app on different devices to confirm its fixed globally.
=> fix select component locking scroll

frontend/src/app/[locale]/(auth)/login/components/PrivacyDialog.tsx, frontend/src/interfaces/models/Common.ts, frontend/src/interfaces/models/PrivacyDialog.ts, frontend/src/interfaces/models/Session.ts, frontend/src/interfaces/models/SessionFeedback.ts, frontend/src/interfaces/models/UserStats.ts
Common.ts missing for shared types 
Added common.ts
None
Tested all pages
None
=> fix(F-417): Centralize types

frontend/src/app/[locale]/(main)/admin/page.tsx, frontend/src/app/[locale]/(main)/dashboard/page.tsx, frontend/src/app/[locale]/(main)/new-conversation-scenario/components/ConversationScenarioForm.tsx, frontend/src/components/common/BackButton.tsx, frontend/src/components/layout/AppHeader.tsx, frontend/src/interfaces/models/ConversationScenario.ts, frontend/src/lib/utils/scoreUtils.ts
=> feat(M): Implement average score calculation and update UI components

backend/app/services/realtime_session_service.py
Enums values are being passed from the frontend. This PR updates the only place where they are used in the backend. Other tests and dummy values should still work with this setup so I have not changed them.
=> fix(M): update get AI voice function to support updated enums from the frontend

frontend/src/app/[locale]/(standalone)/simulation/[id]/components/SimulationHeader.tsx, frontend/src/app/[locale]/(standalone)/simulation/[id]/components/SimulationPage.tsx, frontend/src/app/[locale]/(standalone)/simulation/[id]/page.tsx, frontend/src/services/SessionService.ts
=> feat(M): Integrate session real-time data into simulation Header

backend/app/schemas/scenario_preparation.py, backend/app/services/conversation_scenario_service.py
Add `"categoryId": "salary_discussions"` to scenario prep information
=> Add category id to scenario prep

frontend/src/app/[locale]/(auth)/login/components/ResetPasswordForm.tsx
=> chore: Update supabase redirect

backend/app/services/session_feedback/session_feedback_service.py
- Total training time was not incremented after a session. Should be fixed.
=> Increment Total Training Time in User Profile after Session complete

frontend/src/app/[locale]/(main)/new-conversation-scenario/components/ContextCardButtons.tsx, frontend/src/app/[locale]/(main)/new-conversation-scenario/components/ConversationScenarioForm.tsx, frontend/src/app/[locale]/(main)/new-conversation-scenario/components/PersonaButton.tsx
- Improved Context Cards formatting at step 1
- Improved Situational Cards at step 2
- Removed shadow at the bottom
=> 773 new training improvement

backend/app/services/advisor_service.py, backend/app/services/scenario_preparation/scenario_preparation_service.py, backend/app/services/session_feedback/session_feedback_service.py
- Seems like db sessions are not closed properly.
- Idea: Place all background calls in a try finally block that cleans up the db session afterwards.
=> DB Session Cleanup in Background Task Service

backend/app/services/session_turn_service.py
- Fix problem were stitched audio was displayed with a longer duration that actual file.
=> Fix Audio Stitch Output File Duration

frontend/src/lib/utils/formatDateAndTime.ts
=> fix(M): Conside Timezone in Formatting Date

frontend/src/app/[locale]/(main)/new-conversation-scenario/page.tsx, frontend/src/app/[locale]/(main)/preparation/[id]/page.tsx
=> refactor(M): check if admin dont show SessionLimitReached

backend/app/database.py, backend/app/main.py
Remove create table at every startUp
=> fix(B-123): remove create table at startup
